---
- name: M-Cloud Otomatik Makine Provisioning
  hosts: localhost
  connection: local
  gather_facts: no
  become: false
  vars:
    base_port: 31001

  tasks:
    - name: Mevcut Docker sayisini al
      # Süslü parantezleri sildik, doğrudan sayı alıyoruz
      shell: "docker ps -a --filter name=m-cloud- -q | wc -l"
      register: docker_count
      changed_when: false

    - name: Mevcut LXC sayisini al
      shell: "lxc list --format csv | wc -l"
      register: lxc_count
      ignore_errors: yes
      changed_when: false

    - name: Port Hesapla
      set_fact:
        assigned_port: "{{ base_port | int + (docker_count.stdout | trim | int) + (lxc_count.stdout | trim | int) }}"

    - name: Light Paket - Docker Terminal Baslat
      when: user_choice == 'light_container'
      community.docker.docker_container:
        name: "m-cloud-{{ site_adi }}"
        image: "tsl0922/ttyd:latest"
        command: "ttyd -p 7681 login"
        # Portu açıkça numara olarak gönderiyoruz
        ports:
          - "{{ assigned_port | int }}:7681"
        restart_policy: always
        state: started
